// <auto-generated />
using System;
using AppEducativa.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppEducativa.Api.Data.Migrations
{
    [DbContext(typeof(AppEducativaDbContext))]
    [Migration("20260802020022_EducationalDocuments")]
    partial class EducationalDocuments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.14");

            modelBuilder.Entity("AppEducativa.Api.Models.AI.AiUsageRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClassId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentType")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("GenerationType")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OperationType");

                    b.HasIndex("ClassId", "StartedAt");

                    b.HasIndex("DocumentId", "StartedAt");

                    b.ToTable("AiUsageRecords");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.AI.AssessmentSpecification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BloomLevel")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EducationalDocumentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EvaluationIndicatorId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemCount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalPoints")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("WeightPercentage")
                        .HasPrecision(6, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EducationalDocumentId");

                    b.ToTable("AssessmentSpecifications");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.AI.ClassStructureGeneration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigurationFingerprint")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurriculumReferenceJson")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CurriculumSnapshotId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DifferentiationJson")
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("FormativeAssessmentJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneratedClosureJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneratedDevelopmentJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneratedPurpose")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneratedStartJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneratedTitle")
                        .HasColumnType("TEXT");

                    b.Property<int>("GenerationNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InputTokenCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCurrentVersion")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOutdated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OutputTokenCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestJsonPath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresReview")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResponseJsonPath")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WarningsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClassId", "GenerationNumber")
                        .IsUnique();

                    b.HasIndex("ClassId", "IsCurrentVersion");

                    b.HasIndex("ClassId", "Status");

                    b.ToTable("ClassStructureGenerations");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.AI.ClassStructureRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangeSummary")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClosureJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DevelopmentJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DifferentiationJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EditedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EditedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("FormativeAssessmentJson")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GenerationId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StartJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<bool>("WasManuallyModified")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GenerationId", "IsCurrent");

                    b.HasIndex("GenerationId", "RevisionNumber")
                        .IsUnique();

                    b.ToTable("ClassStructureRevisions");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.AI.EducationalDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BloomLevel")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClassStructureGenerationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigurationFingerprint")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurriculumRelease")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CurriculumSnapshotId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DocumentType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EstimatedDurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FinalizedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCurrentVersion")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOutdated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectiveCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ObjectiveId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresReview")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TotalPoints")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WarningsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClassId", "Status");

                    b.HasIndex("ClassId", "DocumentType", "IsCurrentVersion");

                    b.ToTable("EducationalDocuments");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.AI.EducationalDocumentGeneration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("EducationalDocumentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("GenerationNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InputTokenCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OutputTokenCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestJsonPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseJsonPath")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EducationalDocumentId", "GenerationNumber")
                        .IsUnique();

                    b.ToTable("EducationalDocumentGenerations");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.AI.EducationalDocumentRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangeSummary")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentJsonPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EditedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EditedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EducationalDocumentId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EducationalDocumentId", "RevisionNumber")
                        .IsUnique();

                    b.ToTable("EducationalDocumentRevisions");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.AI.EducationalItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BloomLevel")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("EducationalDocumentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpectedAnswer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Explanation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instructions")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsManuallyEdited")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Points")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SourceGenerationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Statement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TeacherNotes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EducationalDocumentId", "Order");

                    b.ToTable("EducationalItems");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.AI.EducationalItemIndicator", b =>
                {
                    b.Property<Guid>("EducationalItemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EvaluationIndicatorId")
                        .HasColumnType("TEXT");

                    b.HasKey("EducationalItemId", "EvaluationIndicatorId");

                    b.ToTable("EducationalItemIndicators");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.AI.EducationalItemOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EducationalItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Feedback")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EducationalItemId", "Order");

                    b.ToTable("EducationalItemOptions");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Clase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DescripcionCierre")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescripcionDesarrollo")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescripcionInicio")
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("NivelBloom")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ObjetivoAprendizajeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlanificacionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ObjetivoAprendizajeId");

                    b.HasIndex("PlanificacionId", "Numero")
                        .IsUnique();

                    b.ToTable("Clases");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.ClaseIndicadorEvaluacion", b =>
                {
                    b.Property<Guid>("ClaseId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IndicadorEvaluacionId")
                        .HasColumnType("TEXT");

                    b.HasKey("ClaseId", "IndicadorEvaluacionId");

                    b.HasIndex("IndicadorEvaluacionId");

                    b.ToTable("ClaseIndicadores");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Curriculum.Actitud", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Codigo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EstadoRevision")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("NivelAsignaturaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("NivelId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Vigente")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NivelId");

                    b.ToTable("Actitudes");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Curriculum.Asignatura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Asignaturas");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Curriculum.ClaseCurriculumSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActitudesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClaseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoOA")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CurriculumDocumentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescripcionOA")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaSnapshot")
                        .HasColumnType("TEXT");

                    b.Property<string>("HabilidadesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IndicadoresJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ObjetivoAprendizajeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("VersionCurricular")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClaseId")
                        .IsUnique();

                    b.ToTable("ClaseCurriculumSnapshots");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Curriculum.CurriculumDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CurriculumSourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ETag")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorProcesamiento")
                        .HasColumnType("TEXT");

                    b.Property<int>("EstadoProcesamiento")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaDescarga")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaProcesamiento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaPublicacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("HashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroDecreto")
                        .HasColumnType("TEXT");

                    b.Property<string>("RutaArchivoLocal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TextoExtraido")
                        .HasColumnType("TEXT");

                    b.Property<string>("TextoExtraidoPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlOriginal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VersionDetectada")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumSourceId");

                    b.HasIndex("HashSha256")
                        .IsUnique()
                        .HasFilter("\"HashSha256\" <> ''");

                    b.ToTable("CurriculumDocuments");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Curriculum.CurriculumImportBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActiveReviewSessionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CantidadActitudes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadActualizados")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadAdvertencias")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadErrores")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadFuentes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadHabilidades")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadIndicadores")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadOA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadRegistrosNuevos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadSinCambios")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadUnidades")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ConfianzaPromedio")
                        .HasColumnType("REAL");

                    b.Property<string>("CorrectedExtractionJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrectedJsonPath")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CurriculumDocumentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CurriculumReleaseId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CurriculumSourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiffJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExtractionJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtractionJsonPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaTermino")
                        .HasColumnType("TEXT");

                    b.Property<string>("FinalReviewJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("FinalReviewJsonPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mensaje")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalExtractionJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReadyAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReadyBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewContentHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceExternalId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsuarioRevisor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumDocumentId");

                    b.HasIndex("CurriculumSourceId", "Status");

                    b.ToTable("CurriculumImportBatches");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Curriculum.CurriculumRecordSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CurriculumDocumentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntidadId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaVigenciaDesde")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaVigenciaHasta")
                        .HasColumnType("TEXT");

                    b.Property<string>("FragmentoFuente")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PaginaFin")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PaginaInicio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoEntidad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumDocumentId");

                    b.HasIndex("TipoEntidad", "EntidadId");

                    b.ToTable("CurriculumRecordSources");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Curriculum.CurriculumRelease", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CurriculumImportBatchId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ImportBatchCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceDocumentCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumImportBatchId");

                    b.HasIndex("PublishedAt");

                    b.ToTable("CurriculumReleases");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Curriculum.CurriculumReviewChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ChangeType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CurriculumImportBatchId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CurriculumReviewSessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityTemporaryId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCambio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsReverted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NewValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevertedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioRevisor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumImportBatchId");

                    b.HasIndex("CurriculumReviewSessionId");

                    b.ToTable("CurriculumReviewChanges");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Curriculum.CurriculumReviewComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CurriculumReviewSessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityTemporaryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolvedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumReviewSessionId");

                    b.ToTable("CurriculumReviewComments");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Curriculum.CurriculumReviewDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CurriculumReviewSessionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DecidedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecidedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("Decision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityTemporaryId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumReviewSessionId", "EntityTemporaryId");

                    b.ToTable("CurriculumReviewDecisions");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Curriculum.CurriculumReviewSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CurriculumImportBatchId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiffJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaUltimaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("IssuesJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastDiffAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastValidationAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObservacionGeneral")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReadyAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReadyBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewContentHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewContentPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewPackageJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewPackagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("RevisadoPor")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("VersionRevision")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumImportBatchId");

                    b.HasIndex("Estado");

                    b.ToTable("CurriculumReviewSessions");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Curriculum.CurriculumSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AsignaturaEsperada")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dominio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaUltimaRevision")
                        .HasColumnType("TEXT");

                    b.Property<int>("Formato")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NivelEsperado")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoFuente")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasFilter("\"ExternalId\" IS NOT NULL");

                    b.HasIndex("Url");

                    b.ToTable("CurriculumSources");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Curriculum.DocumentoObjetivoAprendizaje", b =>
                {
                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ObjetivoAprendizajeId")
                        .HasColumnType("TEXT");

                    b.HasKey("DocumentoId", "ObjetivoAprendizajeId");

                    b.HasIndex("ObjetivoAprendizajeId");

                    b.ToTable("DocumentoObjetivos");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Curriculum.EjeCurricular", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Codigo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<int>("EstadoRevision")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("NivelAsignaturaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Vigente")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NivelAsignaturaId");

                    b.ToTable("EjesCurriculares");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Curriculum.Habilidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Codigo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EjeCurricularId")
                        .HasColumnType("TEXT");

                    b.Property<int>("EstadoRevision")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("NivelAsignaturaId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Vigente")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NivelAsignaturaId");

                    b.ToTable("Habilidades");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Curriculum.IndicadorEvaluacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Codigo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsSugerido")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstadoRevision")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ObjetivoAprendizajeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Orden")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("UnidadId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Vigente")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ObjetivoAprendizajeId");

                    b.ToTable("IndicadoresEvaluacion");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Curriculum.Nivel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ciclo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("Orden")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("Orden");

                    b.ToTable("Niveles");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Curriculum.NivelAsignatura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activa")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("AsignaturaId")
                        .HasColumnType("TEXT");

                    b.Property<double>("ConfianzaExtraccion")
                        .HasColumnType("REAL");

                    b.Property<bool>("EsContenidoOficial")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstadoRevision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FuenteTipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NivelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreEnNivel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Vigente")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AsignaturaId");

                    b.HasIndex("NivelId", "AsignaturaId")
                        .IsUnique();

                    b.ToTable("NivelesAsignaturas");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Curriculum.ObjetivoAprendizaje", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<double>("ConfianzaExtraccion")
                        .HasColumnType("REAL");

                    b.Property<Guid?>("CurriculumReleaseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EjeCurricularId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsContenidoOficial")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EsObligatorio")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstadoRevision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FuenteTipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NivelAsignaturaId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ObservacionRevision")
                        .HasColumnType("TEXT");

                    b.Property<int>("PublicationStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Vigente")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EjeCurricularId");

                    b.HasIndex("NivelAsignaturaId", "Codigo", "Version")
                        .IsUnique();

                    b.ToTable("ObjetivosAprendizaje");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Curriculum.ObjetivoAprendizajeTransversal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Dimension")
                        .HasColumnType("TEXT");

                    b.Property<int>("EstadoRevision")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("NivelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Vigente")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NivelId");

                    b.HasIndex("Codigo", "NivelId", "Version");

                    b.ToTable("Oats");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Curriculum.Unidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CurriculumReleaseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsContenidoOficial")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstadoRevision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FuenteTipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("HorasPedagogicasSugeridas")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("NivelAsignaturaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Orden")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PublicationStatus")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Vigente")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NivelAsignaturaId", "Numero");

                    b.ToTable("Unidades");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Curriculum.UnidadObjetivoAprendizaje", b =>
                {
                    b.Property<Guid>("UnidadId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ObjetivoAprendizajeId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Orden")
                        .HasColumnType("INTEGER");

                    b.HasKey("UnidadId", "ObjetivoAprendizajeId");

                    b.HasIndex("ObjetivoAprendizajeId");

                    b.ToTable("UnidadObjetivos");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Documento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Asignatura")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AsignaturaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClaseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContenidoGenerado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instrucciones")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NivelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjetivoAprendizaje")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tema")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unidad")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UnidadId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AsignaturaId");

                    b.HasIndex("ClaseId");

                    b.HasIndex("NivelId");

                    b.ToTable("Documentos");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AlternativasJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Enunciado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("IndicadorEvaluacionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NivelBloom")
                        .HasColumnType("TEXT");

                    b.Property<int>("Orden")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Puntaje")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RespuestaCorrecta")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VerboBloom")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoId");

                    b.HasIndex("IndicadorEvaluacionId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Planificacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NivelAsignaturaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NivelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UnidadId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NivelAsignaturaId");

                    b.HasIndex("NivelId");

                    b.HasIndex("UnidadId");

                    b.ToTable("Planificaciones");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.SesionPlanificada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Actividades")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CriterioLogro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("IndicadorEvaluacion")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MinutosEstimados")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NivelBloom")
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ObjetivoAprendizajeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("VerboBloom")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ObjetivoAprendizajeId");

                    b.HasIndex("DocumentoId", "Numero")
                        .IsUnique();

                    b.ToTable("SesionesPlanificadas");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.AI.AssessmentSpecification", b =>
                {
                    b.HasOne("AppEducativa.Api.Models.AI.EducationalDocument", "Document")
                        .WithMany("Specifications")
                        .HasForeignKey("EducationalDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.AI.ClassStructureRevision", b =>
                {
                    b.HasOne("AppEducativa.Api.Models.AI.ClassStructureGeneration", "Generation")
                        .WithMany("Revisions")
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.AI.EducationalDocumentGeneration", b =>
                {
                    b.HasOne("AppEducativa.Api.Models.AI.EducationalDocument", "Document")
                        .WithMany("Generations")
                        .HasForeignKey("EducationalDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.AI.EducationalDocumentRevision", b =>
                {
                    b.HasOne("AppEducativa.Api.Models.AI.EducationalDocument", "Document")
                        .WithMany("Revisions")
                        .HasForeignKey("EducationalDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.AI.EducationalItem", b =>
                {
                    b.HasOne("AppEducativa.Api.Models.AI.EducationalDocument", "Document")
                        .WithMany("Items")
                        .HasForeignKey("EducationalDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.AI.EducationalItemIndicator", b =>
                {
                    b.HasOne("AppEducativa.Api.Models.AI.EducationalItem", "Item")
                        .WithMany("Indicators")
                        .HasForeignKey("EducationalItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.AI.EducationalItemOption", b =>
                {
                    b.HasOne("AppEducativa.Api.Models.AI.EducationalItem", "Item")
                        .WithMany("Options")
                        .HasForeignKey("EducationalItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Clase", b =>
                {
                    b.HasOne("AppEducativa.Api.Models.Curriculum.ObjetivoAprendizaje", "ObjetivoAprendizaje")
                        .WithMany()
                        .HasForeignKey("ObjetivoAprendizajeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppEducativa.Api.Models.Planificacion", "Planificacion")
                        .WithMany("Clases")
                        .HasForeignKey("PlanificacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ObjetivoAprendizaje");

                    b.Navigation("Planificacion");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.ClaseIndicadorEvaluacion", b =>
                {
                    b.HasOne("AppEducativa.Api.Models.Clase", "Clase")
                        .WithMany("Indicadores")
                        .HasForeignKey("ClaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppEducativa.Api.Models.Curriculum.IndicadorEvaluacion", "IndicadorEvaluacion")
                        .WithMany()
                        .HasForeignKey("IndicadorEvaluacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clase");

                    b.Navigation("IndicadorEvaluacion");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Curriculum.Actitud", b =>
                {
                    b.HasOne("AppEducativa.Api.Models.Curriculum.Nivel", "Nivel")
                        .WithMany("Actitudes")
                        .HasForeignKey("NivelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Nivel");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Curriculum.ClaseCurriculumSnapshot", b =>
                {
                    b.HasOne("AppEducativa.Api.Models.Clase", null)
                        .WithOne("CurriculumSnapshot")
                        .HasForeignKey("AppEducativa.Api.Models.Curriculum.ClaseCurriculumSnapshot", "ClaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Curriculum.CurriculumDocument", b =>
                {
                    b.HasOne("AppEducativa.Api.Models.Curriculum.CurriculumSource", "Source")
                        .WithMany("Documents")
                        .HasForeignKey("CurriculumSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Curriculum.CurriculumImportBatch", b =>
                {
                    b.HasOne("AppEducativa.Api.Models.Curriculum.CurriculumDocument", "CurriculumDocument")
                        .WithMany()
                        .HasForeignKey("CurriculumDocumentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AppEducativa.Api.Models.Curriculum.CurriculumSource", "CurriculumSource")
                        .WithMany()
                        .HasForeignKey("CurriculumSourceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CurriculumDocument");

                    b.Navigation("CurriculumSource");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Curriculum.CurriculumRecordSource", b =>
                {
                    b.HasOne("AppEducativa.Api.Models.Curriculum.CurriculumDocument", "Document")
                        .WithMany()
                        .HasForeignKey("CurriculumDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Curriculum.CurriculumReviewChange", b =>
                {
                    b.HasOne("AppEducativa.Api.Models.Curriculum.CurriculumImportBatch", "ImportBatch")
                        .WithMany("ReviewChanges")
                        .HasForeignKey("CurriculumImportBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppEducativa.Api.Models.Curriculum.CurriculumReviewSession", "ReviewSession")
                        .WithMany("Changes")
                        .HasForeignKey("CurriculumReviewSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ImportBatch");

                    b.Navigation("ReviewSession");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Curriculum.CurriculumReviewComment", b =>
                {
                    b.HasOne("AppEducativa.Api.Models.Curriculum.CurriculumReviewSession", "Session")
                        .WithMany("Comments")
                        .HasForeignKey("CurriculumReviewSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Curriculum.CurriculumReviewDecision", b =>
                {
                    b.HasOne("AppEducativa.Api.Models.Curriculum.CurriculumReviewSession", "Session")
                        .WithMany("Decisions")
                        .HasForeignKey("CurriculumReviewSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Curriculum.CurriculumReviewSession", b =>
                {
                    b.HasOne("AppEducativa.Api.Models.Curriculum.CurriculumImportBatch", "ImportBatch")
                        .WithMany("ReviewSessions")
                        .HasForeignKey("CurriculumImportBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportBatch");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Curriculum.DocumentoObjetivoAprendizaje", b =>
                {
                    b.HasOne("AppEducativa.Api.Models.Documento", "Documento")
                        .WithMany("ObjetivosSeleccionados")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppEducativa.Api.Models.Curriculum.ObjetivoAprendizaje", "ObjetivoAprendizaje")
                        .WithMany()
                        .HasForeignKey("ObjetivoAprendizajeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Documento");

                    b.Navigation("ObjetivoAprendizaje");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Curriculum.EjeCurricular", b =>
                {
                    b.HasOne("AppEducativa.Api.Models.Curriculum.NivelAsignatura", "NivelAsignatura")
                        .WithMany("Ejes")
                        .HasForeignKey("NivelAsignaturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NivelAsignatura");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Curriculum.Habilidad", b =>
                {
                    b.HasOne("AppEducativa.Api.Models.Curriculum.NivelAsignatura", "NivelAsignatura")
                        .WithMany("Habilidades")
                        .HasForeignKey("NivelAsignaturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NivelAsignatura");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Curriculum.IndicadorEvaluacion", b =>
                {
                    b.HasOne("AppEducativa.Api.Models.Curriculum.ObjetivoAprendizaje", "ObjetivoAprendizaje")
                        .WithMany("Indicadores")
                        .HasForeignKey("ObjetivoAprendizajeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ObjetivoAprendizaje");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Curriculum.NivelAsignatura", b =>
                {
                    b.HasOne("AppEducativa.Api.Models.Curriculum.Asignatura", "Asignatura")
                        .WithMany("NivelAsignaturas")
                        .HasForeignKey("AsignaturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppEducativa.Api.Models.Curriculum.Nivel", "Nivel")
                        .WithMany("NivelAsignaturas")
                        .HasForeignKey("NivelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asignatura");

                    b.Navigation("Nivel");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Curriculum.ObjetivoAprendizaje", b =>
                {
                    b.HasOne("AppEducativa.Api.Models.Curriculum.EjeCurricular", "EjeCurricular")
                        .WithMany("Objetivos")
                        .HasForeignKey("EjeCurricularId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AppEducativa.Api.Models.Curriculum.NivelAsignatura", "NivelAsignatura")
                        .WithMany("Objetivos")
                        .HasForeignKey("NivelAsignaturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EjeCurricular");

                    b.Navigation("NivelAsignatura");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Curriculum.ObjetivoAprendizajeTransversal", b =>
                {
                    b.HasOne("AppEducativa.Api.Models.Curriculum.Nivel", "Nivel")
                        .WithMany("Oats")
                        .HasForeignKey("NivelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Nivel");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Curriculum.Unidad", b =>
                {
                    b.HasOne("AppEducativa.Api.Models.Curriculum.NivelAsignatura", "NivelAsignatura")
                        .WithMany("Unidades")
                        .HasForeignKey("NivelAsignaturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NivelAsignatura");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Curriculum.UnidadObjetivoAprendizaje", b =>
                {
                    b.HasOne("AppEducativa.Api.Models.Curriculum.ObjetivoAprendizaje", "ObjetivoAprendizaje")
                        .WithMany("Unidades")
                        .HasForeignKey("ObjetivoAprendizajeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppEducativa.Api.Models.Curriculum.Unidad", "Unidad")
                        .WithMany("Objetivos")
                        .HasForeignKey("UnidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ObjetivoAprendizaje");

                    b.Navigation("Unidad");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Documento", b =>
                {
                    b.HasOne("AppEducativa.Api.Models.Curriculum.Asignatura", "AsignaturaNav")
                        .WithMany()
                        .HasForeignKey("AsignaturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppEducativa.Api.Models.Clase", "Clase")
                        .WithMany("Documentos")
                        .HasForeignKey("ClaseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AppEducativa.Api.Models.Curriculum.Nivel", "NivelNav")
                        .WithMany()
                        .HasForeignKey("NivelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AsignaturaNav");

                    b.Navigation("Clase");

                    b.Navigation("NivelNav");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Item", b =>
                {
                    b.HasOne("AppEducativa.Api.Models.Documento", "Documento")
                        .WithMany("Items")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppEducativa.Api.Models.Curriculum.IndicadorEvaluacion", "IndicadorEvaluacion")
                        .WithMany()
                        .HasForeignKey("IndicadorEvaluacionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Documento");

                    b.Navigation("IndicadorEvaluacion");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Planificacion", b =>
                {
                    b.HasOne("AppEducativa.Api.Models.Curriculum.NivelAsignatura", "NivelAsignatura")
                        .WithMany()
                        .HasForeignKey("NivelAsignaturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppEducativa.Api.Models.Curriculum.Nivel", "Nivel")
                        .WithMany()
                        .HasForeignKey("NivelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppEducativa.Api.Models.Curriculum.Unidad", "Unidad")
                        .WithMany()
                        .HasForeignKey("UnidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Nivel");

                    b.Navigation("NivelAsignatura");

                    b.Navigation("Unidad");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.SesionPlanificada", b =>
                {
                    b.HasOne("AppEducativa.Api.Models.Documento", "Documento")
                        .WithMany("Sesiones")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppEducativa.Api.Models.Curriculum.ObjetivoAprendizaje", "ObjetivoAprendizaje")
                        .WithMany()
                        .HasForeignKey("ObjetivoAprendizajeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Documento");

                    b.Navigation("ObjetivoAprendizaje");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.AI.ClassStructureGeneration", b =>
                {
                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.AI.EducationalDocument", b =>
                {
                    b.Navigation("Generations");

                    b.Navigation("Items");

                    b.Navigation("Revisions");

                    b.Navigation("Specifications");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.AI.EducationalItem", b =>
                {
                    b.Navigation("Indicators");

                    b.Navigation("Options");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Clase", b =>
                {
                    b.Navigation("CurriculumSnapshot");

                    b.Navigation("Documentos");

                    b.Navigation("Indicadores");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Curriculum.Asignatura", b =>
                {
                    b.Navigation("NivelAsignaturas");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Curriculum.CurriculumImportBatch", b =>
                {
                    b.Navigation("ReviewChanges");

                    b.Navigation("ReviewSessions");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Curriculum.CurriculumReviewSession", b =>
                {
                    b.Navigation("Changes");

                    b.Navigation("Comments");

                    b.Navigation("Decisions");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Curriculum.CurriculumSource", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Curriculum.EjeCurricular", b =>
                {
                    b.Navigation("Objetivos");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Curriculum.Nivel", b =>
                {
                    b.Navigation("Actitudes");

                    b.Navigation("NivelAsignaturas");

                    b.Navigation("Oats");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Curriculum.NivelAsignatura", b =>
                {
                    b.Navigation("Ejes");

                    b.Navigation("Habilidades");

                    b.Navigation("Objetivos");

                    b.Navigation("Unidades");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Curriculum.ObjetivoAprendizaje", b =>
                {
                    b.Navigation("Indicadores");

                    b.Navigation("Unidades");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Curriculum.Unidad", b =>
                {
                    b.Navigation("Objetivos");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Documento", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("ObjetivosSeleccionados");

                    b.Navigation("Sesiones");
                });

            modelBuilder.Entity("AppEducativa.Api.Models.Planificacion", b =>
                {
                    b.Navigation("Clases");
                });
#pragma warning restore 612, 618
        }
    }
}
